# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: lvoisin- <lvoisin-@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2022/11/07 19:40:41 by lvoisin-      #+#    #+#                  #
#    Updated: 2022/11/07 20:06:44 by lvoisin-      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

SRCS = ft_printf.c 

CC = gcc
CFLAGS = -Wall -Werror -Wextra
NAME = libftprintf
HEADERS = libft/libft.h
